#!/usr/bin/env python3
"""Audit and optionally delete synthetic cycles for selected machines.

Heuristics used:
- rows generated by debug fake endpoint: t_start == t_end OR confidence == 0.95
- rows generated by machine-2 monthly seed: mold_name_snapshot in ('Kalip-1','Kalip-2')
- rows generated by generic fake seed: mold_name_snapshot starts with 'Kalip-'
"""

from __future__ import annotations

import argparse
import sqlite3
from dataclasses import dataclass


DB_PATH = "/home/pi/injection-monitor/backend/data/injection.db"


@dataclass
class Stat:
    machine_id: int
    total: int
    fake_debug_eq_bounds: int
    fake_debug_conf095: int
    fake_future_ts: int
    fake_kalip_prefixed: int
    fake_m2_monthly: int


def _count(cur: sqlite3.Cursor, machine_id: int) -> Stat:
    cur.execute("select count(*) from cycles where machine_id=?", (machine_id,))
    total = int(cur.fetchone()[0] or 0)
    cur.execute(
        "select count(*) from cycles where machine_id=? and t_start=t_end",
        (machine_id,),
    )
    fake_debug_eq_bounds = int(cur.fetchone()[0] or 0)
    cur.execute(
        "select count(*) from cycles where machine_id=? and abs(confidence-0.95)<1e-9",
        (machine_id,),
    )
    fake_debug_conf095 = int(cur.fetchone()[0] or 0)
    cur.execute(
        "select count(*) from cycles where machine_id=? and t_end > CURRENT_TIMESTAMP",
        (machine_id,),
    )
    fake_future_ts = int(cur.fetchone()[0] or 0)
    cur.execute(
        "select count(*) from cycles where machine_id=? and coalesce(mold_name_snapshot,'') like 'Kalip-%'",
        (machine_id,),
    )
    fake_kalip_prefixed = int(cur.fetchone()[0] or 0)
    cur.execute(
        "select count(*) from cycles where machine_id=? and mold_name_snapshot in ('Kalip-1','Kalip-2')",
        (machine_id,),
    )
    fake_m2_monthly = int(cur.fetchone()[0] or 0)
    return Stat(
        machine_id=machine_id,
        total=total,
        fake_debug_eq_bounds=fake_debug_eq_bounds,
        fake_debug_conf095=fake_debug_conf095,
        fake_future_ts=fake_future_ts,
        fake_kalip_prefixed=fake_kalip_prefixed,
        fake_m2_monthly=fake_m2_monthly,
    )


def _delete(cur: sqlite3.Cursor, machine_id: int) -> dict[str, int]:
    out: dict[str, int] = {}
    cur.execute(
        "delete from cycles where machine_id=? and t_start=t_end",
        (machine_id,),
    )
    out["deleted_debug"] = int(cur.rowcount or 0)
    cur.execute(
        "delete from cycles where machine_id=? and t_end > CURRENT_TIMESTAMP",
        (machine_id,),
    )
    out["deleted_future_ts"] = int(cur.rowcount or 0)

    if machine_id == 2:
        cur.execute(
            "delete from cycles where machine_id=? and mold_name_snapshot in ('Kalip-1','Kalip-2')",
            (machine_id,),
        )
        out["deleted_m2_monthly"] = int(cur.rowcount or 0)
    else:
        cur.execute(
            "delete from cycles where machine_id=? and coalesce(mold_name_snapshot,'') like 'Kalip-%'",
            (machine_id,),
        )
        out["deleted_kalip_prefixed"] = int(cur.rowcount or 0)

    # Keep machine mold assignment clean if no cycle left.
    cur.execute("select count(*) from cycles where machine_id=?", (machine_id,))
    left = int(cur.fetchone()[0] or 0)
    out["remaining_cycles"] = left
    if left == 0:
        cur.execute("update machines set current_mold_id=NULL where id=?", (machine_id,))
        out["cleared_current_mold"] = int(cur.rowcount or 0)
    else:
        out["cleared_current_mold"] = 0
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="Delete detected synthetic rows")
    ap.add_argument("--machines", default="1,2,3,4,5,49", help="Comma-separated machine ids")
    args = ap.parse_args()

    mids = [int(x.strip()) for x in args.machines.split(",") if x.strip()]
    con = sqlite3.connect(DB_PATH)
    cur = con.cursor()

    print("AUDIT")
    for mid in mids:
        st = _count(cur, mid)
        print(
            f"mid={st.machine_id} total={st.total} "
            f"fake_debug_eq_bounds={st.fake_debug_eq_bounds} fake_debug_conf095={st.fake_debug_conf095} "
            f"fake_future_ts={st.fake_future_ts} "
            f"fake_kalip_prefixed={st.fake_kalip_prefixed} "
            f"fake_m2_monthly={st.fake_m2_monthly}"
        )

    if not args.apply:
        con.close()
        return

    print("APPLY")
    for mid in mids:
        res = _delete(cur, mid)
        print(f"mid={mid} {res}")
    con.commit()

    print("AFTER")
    for mid in mids:
        st = _count(cur, mid)
        print(
            f"mid={st.machine_id} total={st.total} "
            f"fake_debug_eq_bounds={st.fake_debug_eq_bounds} fake_debug_conf095={st.fake_debug_conf095} "
            f"fake_future_ts={st.fake_future_ts} "
            f"fake_kalip_prefixed={st.fake_kalip_prefixed} "
            f"fake_m2_monthly={st.fake_m2_monthly}"
        )
    con.close()


if __name__ == "__main__":
    main()
